export const SortEnvActionTypes = {
	SET_SORT_TYPE: 'SET_SORT_TYPE',
	SHUFFLE: 'SHUFFLE',
	SHUFFLE_SUCCESS: 'SHUFFLE_SUCCESS'
}

export const SortTypes = {
	BUBBLE_SORT: 'BUBBLE_SORT',
	QUICK_SORT: 'QUICK_SORT'
}