export const SortEnvActionTypes = {
	SET_SORT_TYPE: 'SET_SORT_TYPE',
	SHUFFLE: 'SHUFFLE',
	SHUFFLE_SUCCESS: 'SHUFFLE_SUCCESS',
	DO_NEXT_STEP: 'DO_NEXT_SORT_STEP',
	DO_NEXT_STEP_SUCCESS: 'DO_NEXT_SORT_STEP_SUCCESS'
}

export const SortTypes = {
	BUBBLE_SORT: 'BUBBLE_SORT',
	COCKTAIL_SHAKER_SORT: 'COCKTAIL_SHAKER_SORT'
}
